// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_46uxICKSYynLSUgh1dP3iPsTYD4v2p4',
    appId: '1:264291660789:web:9a9543be8a7204775d26bc',
    messagingSenderId: '264291660789',
    projectId: 'nksproject-38a44',
    authDomain: 'nksproject-38a44.firebaseapp.com',
    storageBucket: 'nksproject-38a44.firebasestorage.app',
    measurementId: 'G-LBNRKYJGZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOPPSQzJu4WHR19KLLTpU9opwfmONcrIk',
    appId: '1:264291660789:android:bd04aa19ac9856b65d26bc',
    messagingSenderId: '264291660789',
    projectId: 'nksproject-38a44',
    storageBucket: 'nksproject-38a44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwZYPbmyIBAdaVPSvyWVAhrGzb8gcSe8Y',
    appId: '1:264291660789:ios:1f1e2841c64e80585d26bc',
    messagingSenderId: '264291660789',
    projectId: 'nksproject-38a44',
    storageBucket: 'nksproject-38a44.firebasestorage.app',
    iosBundleId: 'com.example.appChatHospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwZYPbmyIBAdaVPSvyWVAhrGzb8gcSe8Y',
    appId: '1:264291660789:ios:1f1e2841c64e80585d26bc',
    messagingSenderId: '264291660789',
    projectId: 'nksproject-38a44',
    storageBucket: 'nksproject-38a44.firebasestorage.app',
    iosBundleId: 'com.example.appChatHospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_46uxICKSYynLSUgh1dP3iPsTYD4v2p4',
    appId: '1:264291660789:web:4aec285f5e168f635d26bc',
    messagingSenderId: '264291660789',
    projectId: 'nksproject-38a44',
    authDomain: 'nksproject-38a44.firebaseapp.com',
    storageBucket: 'nksproject-38a44.firebasestorage.app',
    measurementId: 'G-FHVMSBG0PW',
  );
}
